# Generated by Django 3.1.5 on 2021-01-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='事務所名')),
            ],
        ),
        migrations.CreateModel(
            name='Combi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='コンビ名')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.office', verbose_name='所属事務所')),
            ],
        ),
    ]
